backend:
  name: auth0
  domain: dev-4csn0ng87yys2165.us.auth0.com  
  client_id: x37hsvcWcwsZps73UfUjWdpoYj8KP5yf
  audience: https://dev-4csn0ng87yys2165.us.auth0.com/api/v2/  
  redirect_uri: https://kdpropertymanagement.netlify.app/admin/auth/callback
  scope: openid profile email


media_library:
  name: cloudinary
  config:
    cloud_name: dkcafy6wg
    api_key: 474637612327447

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "property"
    label: "Properties"
    folder: "content/properties"
    extension: "json"
    format: "json"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Price per night", name: "price", widget: "number" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Airbnb Link", name: "airbnbLink", widget: "string" }
      - { label: "Booking.com Link", name: "bookingLink", widget: "string" }
      - { label: "Amenities", name: "amenities", widget: "list" }
      - { label: "Images", name: "images", widget: "list", field: { label: "Image", name: "image", widget: "image" } }
